import pandas as pd 
import time
from matplotlib import style
from matplotlib.animation import FuncAnimation
import matplotlib.pyplot as plt
import brainflow
import numpy as np
from brainflow.board_shim import BoardShim, BrainFlowInputParams, LogLevels, BoardIds
from brainflow.data_filter import DataFilter, FilterTypes, AggOperations
from brainflow.ml_model import MLModel, BrainFlowMetrics, BrainFlowClassifiers, BrainFlowModelParams
from matplotlib.animation import FuncAnimation
from random import random
from signals import get_relaxation
from scipy.signal import filtfilt, cheby1, iirnotch



BoardShim.enable_dev_board_logger()
    
params = BrainFlowInputParams()

params.serial_port = "/dev/ttyUSB0" # Change to appropriate port 

board_id = BoardIds.CYTON_BOARD #Using data generated by a synthetic board
# board_id = BoardIds.SYNTHETIC_BOARD

board = BoardShim(board_id, params)

eeg_channels = BoardShim.get_eeg_channels(board_id)
sampling_rate = BoardShim.get_sampling_rate(board_id)
timestamp = BoardShim.get_timestamp_channel(board_id)

board.prepare_session()
board.start_stream()
print(sampling_rate)
def startStream(fig=None):

    data_len = 10
    
    """Lists to store separated eeg signals"""
    eeg1 = []
    eeg2 = []
    eeg3 = []
    eeg4 = []
    eeg5 = []
    eeg6 = []
    eeg7 = []
    eeg8 = []
    
    timex = [] #timestamps
    #while keep_alive == True:
    while board.get_board_data_count() < data_len*sampling_rate:
        time.sleep(0.005)
        
    data = board.get_current_board_data(data_len*sampling_rate)
    # print(data.shape)
    # timex = np.arange(data_len*sampling_rate)
    # eeg5 = data[4]

    eegdf = pd.DataFrame(np.transpose(data[eeg_channels]))
    eegdf_col_names = ["ch1", "ch2", "ch3", "ch4", "ch5", "ch6", "ch7", "ch8"]
    eegdf.columns = eegdf_col_names
    timedf = pd.DataFrame(np.transpose(data[timestamp]))

    #print("Showing data")
        #appending eeg data to lists
    # eeg1.extend(eegdf.iloc[:, 0].values)
    #eeg2.extend(eegdf.iloc[:, 1].values)
    #eeg3.extend(eegdf.iloc[:, 2].values)
    #eeg4.extend(eegdf.iloc[:, 3].values)
    eeg5.extend(eegdf.iloc[:, 4].values)
    # eeg6.extend(eegdf.iloc[:, 5].values)
    # eeg7.extend(eegdf.iloc[:, 6].values)
    # eeg8.extend(eegdf.iloc[:, 7].values)

    timex.extend(timedf.iloc[:, 0].values)  # timestamps

    if(fig != None):
    
        plt.cla()
        # plotting eeg data
        ax1 = fig.add_subplot(121)
        #ax2 = fig.add_subplot(122)

        nyq_freq = sampling_rate / 2
        # eeg5 -= np.nanmean(eeg5, axis = 0)
        # beta, alpha = cheby1(N=2, rp=0.3, Wn=[5 / nyq_freq, 50 / nyq_freq], btype='band', output='ba')
        # eeg5 = filtfilt(beta, alpha, eeg5)

        plt.plot(timex, eeg5,label="Channel 1", color="red")
        # plt.ylim([-20000, 20000])
        plt.axis('off')

        #ax2.plot(timex, eeg2, label="Channel 2", color="blue")
        
    # plt.plot(timex, eeg1, label="Channel 1", color="red")
    # plt.plot(timex, eeg2, label="Channel 2", color="blue")
    # plt.plot(timex, eeg3, label="Channel 3", color="orange")
    # plt.plot(timex, eeg4, label="Channel 4", color="purple")
        # plt.plot(timex, eeg5, label="Channel 5", color="red")
        # plt.plot(timex, eeg6, label="Channel 6", color="blue")
        # plt.plot(timex, eeg7, label="Channel 7", color="orange")
        # plt.plot(timex, eeg8, label="Channel 8", color="purple")

        plt.tight_layout()
    
    
    """Signal processing code"""
      
    """relaxation score calculation"""
    # relax_score = round(random() * 100, 3)# Just some random garbage value. Need to change to ML code
    n_levels = 10
    input_data = np.array([eeg5]).T
    relax_score = 100*get_relaxation(input_data, n_levels = n_levels) / n_levels # Let's try it
    print(relax_score)
    return relax_score

def main(i):

    # style.use('fivethirtyeight')
    plt.title("Live EEG stream from Brainflow", fontsize=15)
    plt.ylabel("Data in millivolts", fontsize=15)
    plt.xlabel("\nTime", fontsize=10)
    plt.axis('off')
    fig = plt.gcf()
    keep_alive = True
    
    
    while keep_alive == True:
        
        startStream(fig)
        # resetting stream so that matplotlib can plot data
        keep_alive = False
    
if __name__ == "__main__":    
    ani = FuncAnimation(plt.gcf(), main, interval=1) 
    plt.tight_layout()
    # plt.autoscale(enable=False, axis="y", tight=True)
    print("Showing")
    plt.show()    
